// <auto-generated />
using System;
using FileToEmailLinker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileToEmailLinker.Migrations
{
    [DbContext(typeof(FileToEmailLinkerContext))]
    [Migration("20231216200544_StartAndEndDateAddedToSchedulationClass")]
    partial class StartAndEndDateAddedToSchedulationClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("FileRefMailingPlan", b =>
                {
                    b.Property<int>("FileNamesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MailingPlanListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileNamesId", "MailingPlanListId");

                    b.HasIndex("MailingPlanListId");

                    b.ToTable("FileRefMailingPlan");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.FileRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileRef");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.MailingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchedulationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchedulationId");

                    b.ToTable("MailingPlan");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.Receiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MailingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailingPlanId");

                    b.ToTable("Receiver");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.Schedulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Recurrence")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedulation");
                });

            modelBuilder.Entity("FileRefMailingPlan", b =>
                {
                    b.HasOne("FileToEmailLinker.Models.Entities.FileRef", null)
                        .WithMany()
                        .HasForeignKey("FileNamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileToEmailLinker.Models.Entities.MailingPlan", null)
                        .WithMany()
                        .HasForeignKey("MailingPlanListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.MailingPlan", b =>
                {
                    b.HasOne("FileToEmailLinker.Models.Entities.Schedulation", "Schedulation")
                        .WithMany()
                        .HasForeignKey("SchedulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedulation");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.Receiver", b =>
                {
                    b.HasOne("FileToEmailLinker.Models.Entities.MailingPlan", null)
                        .WithMany("ReceiverList")
                        .HasForeignKey("MailingPlanId");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.MailingPlan", b =>
                {
                    b.Navigation("ReceiverList");
                });
#pragma warning restore 612, 618
        }
    }
}
