// <auto-generated />
using FileToEmailLinker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileToEmailLinker.Migrations
{
    [DbContext(typeof(FileToEmailLinkerContext))]
    [Migration("20240127113434_SchedulationTableRemoved")]
    partial class SchedulationTableRemoved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.FileRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileRef");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.MailingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileStringList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchedulationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MailingPlan");
                });

            modelBuilder.Entity("FileToEmailLinker.Models.Entities.Receiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Receiver");
                });

            modelBuilder.Entity("MailingPlanReceiver", b =>
                {
                    b.Property<int>("MailingPlanListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MailingPlanListId", "ReceiverListId");

                    b.HasIndex("ReceiverListId");

                    b.ToTable("MailingPlanReceiver");
                });

            modelBuilder.Entity("MailingPlanReceiver", b =>
                {
                    b.HasOne("FileToEmailLinker.Models.Entities.MailingPlan", null)
                        .WithMany()
                        .HasForeignKey("MailingPlanListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileToEmailLinker.Models.Entities.Receiver", null)
                        .WithMany()
                        .HasForeignKey("ReceiverListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
